#!/bin/bash
# Dock launcher: ensure background service is running and open browser

# The service is the LaunchAgent ops-core.wealth_management.app, generated by
# `ops install wealth_management` from ~/.ops-core/jobs.toml (since 2026-09-21;
# before: com.erik.wealth-management.plist with ~/scripts/wm_start.sh).
LABEL="ops-core.wealth_management.app"
SERVICE_URL="http://localhost:8655/wealth"   # baseUrlPath, siehe .streamlit/config.toml
MAX_WAIT=5

# Ensure LaunchAgent is loaded (starts the background service)
if ! launchctl print "gui/$(id -u)/$LABEL" > /dev/null 2>&1; then
    [ -x "$HOME/.local/bin/ops" ] && "$HOME/.local/bin/ops" install wealth_management > /dev/null
fi

# Wait for service to be ready (max 5 seconds)
for i in $(seq 1 $MAX_WAIT); do
    if curl -s "$SERVICE_URL/_stcore/health" > /dev/null 2>&1; then
        break
    fi
    sleep 1
done

# Open browser
open "$SERVICE_URL"
exit 0
